src/Entity/Demandes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\MaxDepth;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DemandesRepository")
 *
 */
class Demandes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
	 * @MaxDepth(2)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sommaire;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $budget;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="demandes")
     * @ORM\JoinTable(name="Categories")
     * @ORM\JoinColumn(nullable=false)
	 * @MaxDepth(2)
     *
     */
    private $categorie;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $deadline;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isOuverte;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isValide;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Citoyen", inversedBy="demandesCreated")
     * @ORM\JoinColumn(nullable=false)
	 * @MaxDepth(2)
     */
    private $createur;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nombreVotes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Citoyen", inversedBy="aVote")
	 * @MaxDepth(2)
     */
    private $voteurs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vote", mappedBy="demande")
	 * @MaxDepth(2)
     */
    private $votes;


    public function __construct()
    {
        $this->voteurs = new ArrayCollection();
        $this->votePour = new ArrayCollection();
        $this->voteContre = new ArrayCollection();
        $this->voteAbstention = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSommaire(): ?string
    {
        return $this->sommaire;
    }

    public function setSommaire(string $sommaire): self
    {
        $this->sommaire = $sommaire;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getBudget(): ?int
    {
        return $this->budget;
    }

    /**
     * @return string
     */
    public function getFormatedBudget()
    {
        return number_format($this->budget, 0, '', ' ');
    }

    public function setBudget(?int $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDeadline(): ?\DateTimeInterface
    {
        return $this->deadline;
    }

    public function setDeadline(\DateTimeInterface $deadline): self
    {
        $this->deadline = $deadline;

        return $this;
    }

    public function getIsOuverte(): ?bool
    {
        return $this->isOuverte;
    }

    public function setIsOuverte(bool $isOuverte): self
    {
        $this->isOuverte = $isOuverte;

        return $this;
    }

    public function getIsValide(): ?bool
    {
        return $this->isValide;
    }

    public function setIsValide(bool $isValide): self
    {
        $this->isValide = $isValide;

        return $this;
    }

    public function getCreateur(): ?Citoyen
    {
        return $this->createur;
    }

    public function setCreateur(?Citoyen $createur): self
    {
        $this->createur = $createur;

        return $this;
    }

    public function getNombreVotes(): ?int
    {
        return $this->nombreVotes;
    }

    public function setNombreVotes(?int $nombreVotes): self
    {
        $this->nombreVotes = $nombreVotes;

        return $this;
    }

    /**
     * @return Collection|Citoyen[]
     */
    public function getVoteurs(): Collection
    {
        return $this->voteurs;
    }

    public function addVoteur(Citoyen $voteur): self
    {
        if (!$this->voteurs->contains($voteur)) {
            $this->voteurs[] = $voteur;
        }

        return $this;
    }

    public function removeVoteur(Citoyen $voteur): self
    {
        if ($this->voteurs->contains($voteur)) {
            $this->voteurs->removeElement($voteur);
        }

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setDemande($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getDemande() === $this) {
                $vote->setDemande(null);
            }
        }

        return $this;
    }



}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Vote;
use App\Form\VoteType;
use App\Repository\DemandesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     */
    public function index(DemandesRepository $demandesRepository)
    {

		return $this->redirectToRoute("vote_index");
    }

    /**
     * @Route("/showoupas", name="show")
     */
    public function show()
    {
        return $this->render('home/show.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Test {% endblock %}

{% block body %}






    {% for lien in pagination.countDemandes %}
        <a href="{{ path("vote_index", {'page' : lien}) }}">{{ lien }}</a>
    {% endfor %}



            <div class="columns">
                <h1>{{ demande.titre }}</h1>
                <p>{{ demande.contenu }}</p>
                <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Pour'}) }}">Vote Pour</a>
                <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Contre'}) }}">Vote Contre</a>
                <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Abstention'}) }}">Vote Abstention</a>
                <div>


                  {% endfor %}
                <div class="level has-text-grey">
                    <div class="level-left has-text-weight-semibold">
                        <p>Titre</p>
                    </div>
                    <div class="level-right">
                        <p>Cree le jkdjkdbchdb</p>
                    </div>
                </div>

                <div class="level">
                    <p>On sait depuis longtemps que travailler avec du texte lisible et
                        contenant du sens est source de distractions, et empêche de se
                        concentrer sur la mise en page elle-même.</p>
                </div>
            </div>

            <div class="column center">
                <div class="level">
                    <div class="level-item">
                        <p class="has-text-weight-semibold pt-3">Fonds demandés</p>
                    </div>

                </div>
                <div class="level">
                    <div class="level-item">
                        <p class="has-text-weight-bold">15 000€</p>
                    </div>
                </div>
                <div class="level">
                    <div class="level-item">
                        <progress class="progress is-info" value="15" max="100">15%</progress>
                    </div>
                </div>
                <div class="level">
                    <div class="level-item">
                        <p>vote deadline : <span>01/01/2020</span></p>
                    </div>
                </div>
            </div>

            <div class="column">
                <div class="level">
                    <div class="level-left">
                        <div class="level-item">
                            <span class="icon">
                              <i class="fas fa-home"></i>
                            </span>
                            <p>38 %</p>
                        </div>
                    </div>
                    <div class="level-right">
                        <div class="level-item">
                            <p>Contre <span>988 050</span></p>
                        </div>
                    </div>
                </div>
                <div class="level">
                    <div class="level-item -mt-1">
                        <progress class="progress is-danger" value="15" max="100">15%</progress>
                    </div>
                </div>

                <div class="level">
                    <div class="level-left">
                        <div class="level-item">
                            <span class="icon">
                              <i class="fas fa-home"></i>
                            </span>
                            <p>38 %</p>
                        </div>
                    </div>
                    <div class="level-right">
                        <div class="level-item">
                            <p>Pour <span>988 050</span></p>
                        </div>
                    </div>
                </div>
                <div class="level">
                    <div class="level-item -mt-1">
                        <progress class="progress is-success" value="15" max="100">15%</progress>
                    </div>
                </div>

                <div class="level">
                    <div class="level-left">
                        <div class="level-item">
                            <span class="icon">
                              <i class="fas fa-home"></i>
                            </span>
                            <p>38 %</p>
                        </div>
                    </div>
                    <div class="level-right">
                        <div class="level-item">
                            <p>Neutre <span>988 050</span></p>
                        </div>
                    </div>
                </div>

                <div class="level">
                    <div class="level-item -mt-1">
                        <progress class="progress" value="15" max="100">15%</progress>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns bordered white-block" style="background-color: #FFFFFF;">
            <div class="column">
                <div class="level has-text-centered">
                    <div class="level-item">
                        <a class="button is-primary is-outlined">Detail</a>
                    </div>

                    <div class="level-item has-text-centered">
                        <a class="button is-primary is-outlined">Qui a voté ?</a>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('main') }}
{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Titre : {{ demande.titre }}
                </h1>
                <h2 class="subtitle">

                </h2>
            </div>
        </div>
    </section>

    <div class="container">
    <div class="columns">
        <div class="column">
            <a href="{{ path('demandes_ouvertes') }}" class="button is-primary">liste des demandes</a>
        </div>
    </div>
        <div class="colmuns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Sommaire</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <p>{{ demande.sommaire }}</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colmuns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Description</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <p>{{ demande.contenu }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="colmuns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Montant</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <p>
                                {{ demande.formatedBudget }} €
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="columns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Ils ont voté</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">

                            <div class="level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <span class="icon">
                                          <i class="fas fa-home"></i>
                                        </span>
                                        <p>38 %</p>
                                    </div>
                                </div>
                                <div class="level-right">
                                    <div class="level-item">
                                        <p>Pour <span>{{ demande.nombreVotes }} votants</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="level">
                                <div class="level-item -mt-1">
                                    <progress class="progress is-danger" value="15" max="100">15%</progress>
                                </div>
                            </div>


                            <div class="level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <span class="icon">
                                          <i class="fas fa-home"></i>
                                        </span>
                                        <p>38 %</p>
                                    </div>
                                </div>
                                <div class="level-right">
                                    <div class="level-item">
                                        <p>Pour <span>988 050</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="level">
                                <div class="level-item -mt-1">
                                    <progress class="progress is-success" value="15" max="100">15%</progress>
                                </div>
                            </div>


                            <div class="level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <span class="icon">
                                          <i class="fas fa-home"></i>
                                        </span>
                                        <p>38 %</p>
                                    </div>
                                </div>
                                <div class="level-right">
                                    <div class="level-item">
                                        <p>Pour <span>988 050</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="level">
                                <div class="level-item -mt-1">
                                    <progress class="progress" value="15" max="100">15%</progress>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if not app.user.aVote %}
        <div class="colmuns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Je vote</h3>
            </div>
        </div>
        <div class="columns">

            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <div class="buttons has-addons is-centered">
                                <div class="field is-grouped">
                                    <div class="column">
                                        <p class="control">
                                            <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Pour'}) }}"
                                               class="button is-link">
                                                Pour
                                            </a>
                                        </p>
                                    </div>
                                    <div class="column">
                                        <p class="control">
                                            <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Abstention'}) }}"
                                               class="button">
                                                Abstention
                                            </a>
                                        </p>
                                    </div>
                                    <div class="column">
                                        <p class="control">
                                            <a href="{{ path("vote_avote", {'id' : demande.id, 'vote':'Contre'}) }}"
                                               class="button is-danger">
                                                Contre
                                            </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       {% else %}
        <div class="colmuns">
            <div class="column">
                <h3 class="title is-3 has-text-grey">Mon vote</h3>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="columns">
                    <div class="column">
                        <div class="box">
                            <div class="buttons has-addons is-centered">
                                <span class="button">{{ demande.votes.get('etat') }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% endif %}


{% endblock %}